# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "LQqfjW1iCstGU8zuyWv5bDGPSQC1xqu+M++vBI6WdwiFQc+//OnBqynqa785Tq0kPjPzhWH6jobr97fpPoZ+R11k2NqOl9cuW63WXj9cA1Ai8vQB/CvahaiaVlrDIDItGHO3WmeQIATwzY5Fb0tZCBKmkaLkB9hm7W2QsUiMOQYvk3teaIHf4bAgmvz8gpJSPwvV/ENf603dL7QO4mP17giXELWOFh3MT6t8p6Yp9H1wSg/F55UpWk+HcDKnb1o4r+SZOa1sDtmV3RFGRkk6O5rvmcor8jAIbdA3ROFB3k1tlCs8+rJNKiq6PquqjXHAA+cdhGlffSjoNLJDe7F1h7EMHRAZekymqEpNQ6Ah775bo9UPVLnLtl62ko4cvz4uQo7LC+58rqA8107IkhE+wbDT2F3OR8gGowkopfAFNf4pMOLIRgJgWVHYLK6TvoHaFzahlyieu2KOjUHhoXEziRxL9sZglxi5Clf2HQxNfYHrMikP+uQR8z0fbAi38yVZeE10x2vCeeIF+0lGqiJOzilIZutmXmjLg+HuFLPqut9LAr15NMwhupCasSsvMbQ2yCipKjozUizrHJvwWIdqtmD7UNoedRbQk6k4J6G87HQgFsjwpmTd+PGW9eFyU/4c+XI5iSp7re11uOv3rFLwpI5N+SJieMLUGEsIT/i5IM8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
